on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker

    steps:
      - run: apt update
      - run: apt install --assume-yes --auto-remove --no-install-recommends 7zip ffmpeg yt-dlp

      - run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/bin/yt-dlp
          chmod a+rx /usr/bin/yt-dlp

      - uses: https://github.com/denoland/setup-deno@v2

      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - run: echo "$COOKIES" > cookies.txt
        env:
          COOKIES: ${{ secrets.COOKIES }}

      - run: make download
      - run: make build

      - uses: forgejo/upload-artifact@v5
        with:
          name: NieR Music.zip
          path: NieR Music.zip
          compression-level: 9
          if-no-files-found: error
